### PR TITLE
St company field in shipping

### PR DESCRIPTION
**Pull request by Rmh1978**
Created company_name_ST and all the associate fixes to use it in Shipping.

The only thing i could not figure out was to populate and change the dropdown `$this->lists['is_company']`
in component/admin/views/addorder_detail/tmpl/default.php:506 when :
Add new order, select a user that has saved shipping user, and select a ST user for shipping. 
Then this function `onchange="showOfflineCompanyOrCustomer(this.value);"` populate the shipping fields with the ST user details. But it does not change the is_company selection.

It is a small thing and rarely used in backend but still.

Issue #5319 

@lunguyenhat

### CODE REVIEW

**Comment by NguyenBao10** [comment]
Thank you @Rmh1978 , let us check the things you could not figure out and add to this PR

**Review by lunguyenhat — DISMISSED** [review]

**Comment by NguyenBao10** [comment]
Thank you @Rmh1978 , our QA will check one more time just for sure, and i will try to figure out the small thing you mention in the meantime

**Comment by VanTrieuThanh** [comment]
FE 
1. Checkout page 
Popup create/detail shipping address is missing 
image
Admin
1. Order 
Create new order select user has create not tick the type user
image
After create the new user and Apply user the Company Customer has unselect 
image
2 User 
Shipping Infor list -The Company name is missing (related with FE missing field)
image
Shipping Infor - Detail/Create item missing the Company name field 
image
3. Shipping can't view the detail shipping 
image

anh @NguyenBao10 , @Rmh1978 help me check again some my noted when I get your code Ronni's

**Comment by Rmh1978** [comment]
Hi @VanTrieuThanh 

**1. Checkout page FE**
Did you add the tag {company_name_st} in the shipping_template?

I made a comit with a update for the default template to add the tags.


**2 Order
Create new order select user has create not tick the type user**
I used the wrong is_company list. Changed to ST and it is now ticked.


**After create the new user and Apply user the Company Customer has unselect**
Same as above (2)


**2 User
Shipping Infor list -The Company name is missing (related with FE missing field)**
Well yes, or more that there is not saved a Company name on the ST user, so nothing to show. It shows when there is a company name.



**Shipping Infor - Detail/Create item missing the Company name field**
True. I did not get around that view. I dont think this is used much. I never used this view in my years of use of redShop, so i down priotized it for now. I will add it later.


**Shipping can't view the detail shipping**
What view is this?
I opened  default_shipping > rates   to get the same url like you and it displayed just fine.

**Comment by VanTrieuThanh** [comment]
@Rmh1978 I has get your new code and some noted has resolved but at the **Admin** it has some error, notice. You can review it

FE - has show on
1. Create new account has show on at Shipping Address
image
2. User detail has show on at Shipping Address
image

**Admin** - need review from you
1. Create Order 
Shipping Address show on the Registered as field  (it has ready on the Billing Address) - need fix (I has compare with other site it not show on this field)
image
After create the user in Order has show on the Notice at the Registered as field
image
Order detail Company name has show on 
image
2. All Template detail item show error page (I throught to view the shipping_template item)
image
image
3. **Shipping Infor - Detail/Create item missing the Company name field
True. I did not get around that view. I dont think this is used much. I never used this view in my years of use of redShop, so i down priotized it for now. I will add it later.**
- You can create new issue to add it later or we can ignore 
4. **Shipping can't view the detail shipping
What view is this?**
From Shipping list 
image
image

**Comment by Rmh1978** [comment]
**FE - has show on**
In frontend there is field check that changes is_company depending on if the company field is populated or not. That is why the text says it not required. Can be enhanced later with the new ST customer/ company checkbox (see below).

**Admin coments**
The 3 points are all related to the comment i described in the PR description to @NguyenBao10 
I/ we need to build a registrer customer/ company checkbox list that has a new function in js that is a copy of :
onchange="showOfflineCompanyOrCustomer(this.value);"
but only for ST so it does not change BT fields.

**All Template detail item show error page (I throught to view the shipping_template item)**
This is strange. Both my templates and the shipping method/ rates loads correct.
I have only copied the changed files to my testsite and installed a complete build release from this branch.
@NguyenBao10  can you maybe help to investigate where the error comes from?

**You can create new issue to add it later or we can ignore**
For now i will ignore and make a small fix comit with other things later.
I couldnt easyly find where the field form was created, so i skipped it because it is not that often used.
@NguyenBao10  can you direct me to what file this is compiled in?
User shipping detail - New (admin)

I am off for vacation later today, so I am "offline" a couple of weeks.

**Comment by Rmh1978** [comment]
@VanTrieuThanh 
Now i got the time and got the test site working probertly. So made some changes and it should work now.
I have the broken templates is not a issue anymore.

Remember to add
{company_name_st_lbl}{company_name_st}
to your shipping template.

**Comment by VanTrieuThanh** [comment]
@Rmh1978 I still got error when go to the shipping_template item
image

**Comment by Rmh1978** [comment]
@VanTrieuThanh   thats weird. I just made a new install with package and my shipping_template
administrator/index.php?option=com_redshop&view=template&layout=edit&id=451
opens just fine.

@NguyenBao10  can you try to install this PR and see if you get the same error as Van, and if yes see where the error comes from, so i can fix it?
Noname

**Comment by Rmh1978** [comment]
@NguyenBao10 can you check this PR and check if you get same template error as @VanTrieuThanh 

It is all good on my end, no errors. Could be nice to close and merge.

**Pull request closed without merging**
