### PR TITLE
REDSHOP-5947 [Reractor][Component][Site] Move to use Twig for view Account billto

### PR DESCRIPTION
**Pull request by hungnguyenckc**

### CODE REVIEW

**Review by anhredweb — DISMISSED** [review]

**Comment by VanTrieuThanh** [comment]
@trangredweb help me check fail drone

**Comment by NguyenTrang091296** [comment]
> @trangredweb help me check fail drone

Let me check

**Review by anhredweb — APPROVED** [review]

**Comment by NguyenTrang091296** [comment]
Hi @anhredweb. PR pass drone server now.

**Comment by anhredweb** [comment]
@NguyenTrang091296 Thanks, I's been merged

**Pull request merged**
