### PR TITLE
Alert plugin

### PR DESCRIPTION
**Pull request by Rmh1978**
I changed some things around the alert plugin.

I have described the changes in every comit.

Testet and working in RS 2.1.2.1 and made the some changes to work in 3.0.3

@NguyenBao10 
@lunguyenhat

### CODE REVIEW

**Review by NguyenBao10 — DISMISSED** [review]

**Comment by NguyenBao10** [comment]
thanks @Rmh1978 , our QA will check one more time just for sure

**Comment by VanTrieuThanh** [comment]
it has changed on the plugin 
image
Alert for register 
image
@Rmh1978 help me check again when checkout the cart to get the alert for order it show error 
image
Create order in admin - don't get alert for order, but alert for stock room working on (the alert for order will show on when user create order at FE, right? @Rmh1978 )
image

**Comment by Rmh1978** [comment]
Hi @VanTrieuThanh 

**it has changed on the plugin**
I guess this coment is OK for you?
Could you maybe write it something like this:
"it has changed on the plugin - OK"
Just so i dont get confused if it needs change or is approoved :-)


**Alert for register**
The alert gets saved but i can see that it has not saved Company name, first and last name (the info who registered).
I have only live testet it and working on RS 2.1.2.1 as my frontend don´ t work on my 3.0.3 testsite.
But i guess $billingAddresses has to be changed to $post.
So has to wait till my FE is working to finish this.

**help me check again when checkout the cart to get the alert for order it show error**
I forgot to update the format price function. I changed it in a new comit.


**Create order in admin - don't get alert for order, but alert for stock room working on (the alert for order will show on when user create order at FE, right?**
Yes thats the way it is made in the core. It makes sense that you should get a notification in BE for a order you created yourself.
But stockroom is always important to know about.

**Comment by VanTrieuThanh** [comment]
@Rmh1978 
**I guess this comment is OK for you?** Yes. it has OK with me. I'm sorry has made you confuse 

**Alert for register** -> let ping me when it has done 

**I forgot to update the format price function. I changed it in a new commit.** I has checked look like you missing push the code 
image

**Comment by Rmh1978** [comment]
@VanTrieuThanh 

I will ping you when i updated the code. 

I pushed it now.

**Comment by Rmh1978** [comment]
Now all should be fixed. Please verify @VanTrieuThanh

**Comment by Rmh1978** [comment]
@VanTrieuThanh  bump :-)

**Comment by VanTrieuThanh** [comment]
image
@Rmh1978 I has get your code and it has work (resolved item I got)

**Comment by Rmh1978** [comment]
@anhredweb please merge.

**Pull request closed without merging**
