### PR TITLE
REDSHOP-6130 Discount calculation double price when 2x click

### PR DESCRIPTION
**Pull request by NguyenBao10**

### CODE REVIEW

**Review by anhredweb — DISMISSED** [review]

**Comment by Rmh1978** [comment]
Works. Thank you.

**Comment by NguyenTrang091296** [comment]
Please help me review PR when you have free time cc @anhredweb

**Review by anhredweb — DISMISSED** [review]

**Comment by NguyenTrang091296** [comment]
Scrutinizer still fail cc a @anhredweb

**Comment by NguyenTrang091296** [comment]
Please help me review PR again cc a @anhredweb

**Review by anhredweb — APPROVED** [review]

**Pull request merged**
